name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script with SECRET KEY21
        run: |
          python soccer_dashboard_01.py
        env:
          KEY21: ${{ secrets.KEY21 }}  # Access the secret here
